feat: add current HIP-24 spec
hashgraph/hedera-sdk-reference pull request #10
Opened 2021-09-28 06:32 UTC by janaakhterov

Signed-off-by: Daniel Akhterov <daniel@launchbadge.com>

**Description**:

**Related issue(s)**:

Fixes #9 

**Notes for reviewer**:

**Checklist**

- [X] Documented (Code comments, README, etc.)

2021-10-04 21:57 UTC, SimiHunjan commented on _sidebar.md
>          * [`TokenUpdateTransaction`](reference/token/TokenUpdateTransaction.md)
We are missing `TokenPauseTransaction` from this list.

2021-10-04 22:08 UTC, SimiHunjan commented on reference/token/TokenPauseTransaction.md
> +- `Duration` is `number` and is the number of seconds
I think this line was accidentally added here.

2021-10-04 22:10 UTC, SimiHunjan commented on reference/token/TokenUpdateTransaction.md
> +
Should each of the examples be updated to show all of the fields that can be set?

2021-10-04 22:11 UTC, SimiHunjan commented on reference/token/TokenCreateTransaction.md
> +
Should each of the examples be updated to show all of the fields that can be set?

2021-10-04 22:12 UTC, SimiHunjan requested changes
please see comments

2021-10-04 23:14 UTC, janaakhterov commented on reference/token/TokenUpdateTransaction.md
> +
The examples aren't meant to show you how to set _each_ field. They're simply supposed to show you the pattern of how to set fields in a particular language. For instance in Java to set fields you'd use `set<field name in title case>()` while in Go you'd do `Set<field name in title case>()`. The examples are meant to be simple enough that someone can look at them and get the gist of how to use the request type. This _can_ be changed, but that is the current goal of the examples which is why the examples weren't updated with `setPauseKey(pauseKey)`

2021-10-05 02:43 UTC, SimiHunjan approved these changes

2021-10-05 19:57 UTC, janaakhterov commented
I discussed this a bit yesterday with @andrix10 and he had a good point. Why are we treating `TokenPauseStatus` differently than `TokenFreezeStatus` or `TokenKycStatus`. We we should update this PR to use a nullable boolean instead of an enum to be consistent with the other two statuses. Thoughts @Sean-Tedrow-LB @valtyr-naut

2021-10-06 05:22 UTC, SimiHunjan approved these changes

2021-10-07 04:23 UTC, merged