Feature/expected decimals and ledger
hashgraph/hedera-sdk-reference pull request #20
Opened 2021-12-30 02:30 UTC by janaakhterov

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-12-30 03:06 UTC, Sean-Tedrow-LB approved these changes

2021-12-30 07:03 UTC, andrix10 approved these changes

2021-12-30 07:28 UTC, andrix10 requested changes

2021-12-30 07:28 UTC, andrix10 commented on reference/cryptocurrency/TransferTransaction.md
> +##### `getTokenIdDecimals`: `Map` < [`TokenId`](reference/token/TokenId.md), `Uint64` >
Shouldn't this be a map of TokenId to Uint32?

2022-01-04 00:25 UTC, Sean-Tedrow-LB requested changes

2022-01-04 00:25 UTC, Sean-Tedrow-LB commented on reference/cryptocurrency/TransferTransaction.md
> +The the expected decimals per token ID
Only need one "the"

2022-01-04 00:25 UTC, Sean-Tedrow-LB commented on reference/cryptocurrency/TransferTransaction.md
> +##### `getTokenIdDecimals`: `Map` < [`TokenId`](reference/token/TokenId.md), `Uint32` >
This does not match [the implementation I wrote for the Java SDK](https://github.com/hashgraph/hedera-sdk-java/blob/30cb10c1d83cd0af948271d692d9e72db618ad93/sdk/src/main/java/com/hedera/hashgraph/sdk/TransferTransaction.java#L63-L71).  Which one should be changed?

2022-01-04 01:21 UTC, andrix10 approved these changes

2022-01-04 01:21 UTC, Sean-Tedrow-LB approved these changes

2022-01-04 01:26 UTC, valtyr-naut approved these changes
lgtm

2022-01-04 01:36 UTC, merged