HIP-336
hashgraph/hedera-sdk-reference pull request #27
Opened 2022-01-26 01:09 UTC by janaakhterov

2022-01-26 03:55 UTC, Sean-Tedrow-LB requested changes

2022-01-26 03:55 UTC, Sean-Tedrow-LB commented on reference/cryptocurrency/AccountAllowanceApprovalTransaction.md
> +    .addHbarApproval(accountId, )
Update this

2022-01-26 22:20 UTC, Sean-Tedrow-LB approved these changes

2022-01-27 17:12 UTC, SimiHunjan approved these changes

2022-01-28 20:44 UTC, Sean-Tedrow-LB approved these changes

2022-01-29 02:31 UTC, Sean-Tedrow-LB approved these changes

2022-01-29 03:50 UTC, merged